# Changes here will be overwritten by Copier
_commit: 1.2.0-2-g2cb067a
_src_path: python-project-template/
author_email: delucchi@andrew.cmu.edu
author_name: LINCC-Frameworks
create_example_module: false
module_name: hipscat_import
preferred_linter: pylint
project_name: hipscat-import
use_isort: true
