[project]
name = "hipscat-import"
license = {file = "LICENSE"}
readme = "README.md"

classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]
version = "0.0.1"

requires-python = ">=3.8"
dependencies = [
    "dask",
    "dask[distributed]",
    "healpy",
    "hipscat",
    "pandas",
    "pyarrow",
    "tqdm",
]

# On a mac, install optional dependencies with `pip install '.[dev]'` (include the single quotes)
[project.optional-dependencies]
dev = [
    "pytest", 
    "pytest-cov",
]

[metadata]
description = "HiPSCat import"
long_description = { file = "README.md" }
url = "https://github.com/astronomy-commons/hipscat-import"

[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"
